# Generated by Django 4.2.1 on 2023-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratchet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_full_name', models.CharField(default='Пример Пример Примеров', max_length=200, verbose_name='Полное имя')),
                ('employee_age', models.IntegerField()),
                ('employee_specialization', models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Педиатр', 'Педиатр'), ('Невролог', 'Невролог'), ('Реабилитолог', 'Реабилитолог'), ('Стоматолог', 'Стоматолог'), ('Лор', 'Лор'), ('Травмотолог', 'Травмотолог')], max_length=50, verbose_name='Специализация')),
                ('employee_experience', models.IntegerField()),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='Doctors/')),
            ],
        ),
    ]
