# Generated by Django 4.2.1 on 2023-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratchet', '0002_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
