# Generated by Django 4.2.1 on 2023-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratchet', '0003_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание/достижения'),
        ),
    ]
